
// utils/scriptsList.js

const scripts = [
  { src: "../temp/ajax/libs/jquery/1.8.3/jquery.min.js" },
  { src: "../temp/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" },
  { src: "../temp/js/plugins/charts/excanvas.min.js" },
  { src: "../temp/js/plugins/charts/jquery.flot.js" },
  { src: "../temp/js/plugins/charts/jquery.flot.orderBars.js" },
  { src: "../temp/js/plugins/charts/jquery.flot.pie.js" },
  { src: "../temp/js/plugins/charts/jquery.flot.resize.js" },
  { src: "../temp/js/plugins/charts/jquery.sparkline.min.js" },
  { src: "../temp/js/plugins/tables/jquery.dataTables.js" },
  { src: "../temp/js/plugins/tables/jquery.sortable.js" },
  { src: "../temp/js/plugins/tables/jquery.resizable.js" },
  { src: "../temp/js/plugins/forms/jquery.autosize.js" },
  { src: "../temp/js/plugins/forms/jquery.uniform.js" },
  { src: "../temp/js/plugins/forms/jquery.inputlimiter.min.js" },
  { src: "../temp/js/plugins/forms/jquery.tagsinput.min.js" },
  { src: "../temp/js/plugins/forms/jquery.maskedinput.min.js" },
  { src: "../temp/js/plugins/forms/jquery.autotab.js" },
  { src: "../temp/js/plugins/forms/jquery.select2.min.js" },
  { src: "../temp/js/plugins/forms/jquery.dualListBox.js" },
  { src: "../temp/js/plugins/forms/jquery.cleditor.js" },
  { src: "../temp/js/plugins/forms/jquery.ibutton.js" },
  { src: "../temp/js/plugins/forms/jquery.validationEngine-en.js" },
  { src: "../temp/js/plugins/forms/jquery.validationEngine.js" },
  { src: "../temp/js/plugins/uploader/plupload.js" },
  { src: "../temp/js/plugins/uploader/plupload.html4.js" },
  { src: "../temp/js/plugins/uploader/plupload.html5.js" },
  { src: "../temp/js/plugins/uploader/jquery.plupload.queue.js" },
  { src: "../temp/js/plugins/wizards/jquery.form.wizard.js" },
  { src: "../temp/js/plugins/wizards/jquery.validate.js" },
  { src: "../temp/js/plugins/wizards/jquery.form.js" },
  { src: "../temp/js/plugins/ui/jquery.collapsible.min.js" },
  { src: "../temp/js/plugins/ui/jquery.breadcrumbs.js" },
  { src: "../temp/js/plugins/ui/jquery.tipsy.js" },
  { src: "../temp/js/plugins/ui/jquery.progress.js" },
  { src: "../temp/js/plugins/ui/jquery.timeentry.min.js" },
  { src: "../temp/js/plugins/ui/jquery.colorpicker.js" },
  { src: "../temp/js/plugins/ui/jquery.jgrowl.js" },
  { src: "../temp/js/plugins/ui/jquery.fancybox.js" },
  { src: "../temp/js/plugins/ui/jquery.fileTree.js" },
  { src: "../temp/js/plugins/ui/jquery.sourcerer.js" },
  { src: "../temp/js/plugins/others/jquery.fullcalendar.js" },
  { src: "../temp/js/plugins/others/jquery.elfinder.js" },
  { src: "../temp/js/plugins/forms/jquery.mousewheel.js" },
  { src: "../temp/js/plugins/ui/jquery.easytabs.min.js" },
  { src: "../temp/js/files/bootstrap.js" },
  { src: "../temp/js/files/functions.js" },
  { src: "../temp/js/charts/chart.js" },
  { src: "../temp/js/charts/hBar_side.js" },
  ];
  
  export default scripts;
  